### ISSUE TITLE
Input & output node names

### ISSUE THREAD

**Issue by cwlroda** [JuanDuGit/DH3D#10]
Hi, thank you for the great work!

I intend to modify the code and run it using the `tf.Session` equivalent in Tensorflow C++ API.

From the function `compute_local` in [model.py](https://github.com/JuanDuGit/DH3D/blob/master/core/model.py), I see that the pointcloud input for the input dict is `points`, which is derived from 

```
points = tf.concat(pcdset, 0, name='pointclouds')
```

in the function `build_graph`.

However, when I import the meta graph and list the nodes, I am unable to find any node named `pointclouds`.

May I know how I can access it and similarly the output node names when I run my session? Apologies if my description sounds confusing as I am quite new to this.

**Comment by JuanDuGit** [comment]
Hi, what's your output of the node list specifically?

**Comment by cwlroda** [comment]
The link to the text file containing the node list is [here](https://github.com/cwlroda/DH3D/blob/master/nodes.txt) (not posting directly as it's quite long)

This is the code I'm running to generate the node list:
```
with tf.Session(graph=tf.Graph()) as sess:
        # Restore local model
        loader = tf.compat.v1.train.import_meta_graph(
            trained_checkpoint_prefix + ".meta"
        )
        loader.restore(sess, trained_checkpoint_prefix)

        graph_def = tf.get_default_graph().as_graph_def()

        # All nodes to list
        node_list = [n.name for n in graph_def.node]
```

**Comment by JuanDuGit** [comment]
Then "pointcloud" exists as a tensor instead of a node in the graph. That's why it does not appear in your node list. 
It is not obvious to me what you are going to do with `tf.Session`, but it's not a proper way to run inference with a model restored from the metagraph as said in [this link](https://tensorpack.readthedocs.io/en/latest/tutorial/inference.html#step-1-build-the-model-graph).
In our evaluation scripts, we use `OfflinePreditor` from tensorpack to do offline inference: https://github.com/JuanDuGit/DH3D/blob/b1ec580a8f24697559ea497d875f657387d0f112/evaluate/local_eval/localdesc_extract.py#L81 
You can refer to its [docs](https://tensorpack.readthedocs.io/en/latest/modules/predict.html#tensorpack.predict.OfflinePredictor) for details on how it builds a graph and creates a session, etc .

**Comment by cwlroda** [comment]
I have read through the tensorpack docs and figured out how to export to SavedModel format, thank you for your help!

Here's the skeleton code if anyone reading this in the future would like to perform the same task.

```
pred_config = PredictConfig(
    model=DH3D(config),
    session_init=SmartInit(trained_checkpoint_prefix),
    input_names=[
        "pointclouds",
    ],
    output_names=["xyz_feat", "xyz_feat_att"],
)

ModelExporter(pred_config).export_serving(export_dir)
```
