### ISSUE TITLE
what kind of graphics driver do you use?

### ISSUE THREAD

**Issue by JustWon** [JuanDuGit/DH3D#3]
In my case, I am using NVIDIA Geforce RTX 2080.
But RTX 2080 only supports CUDA 10.0 above.
https://github.com/tensorflow/tensorflow/issues/22900

But the tensorflow v1.9.0, v1.10.0 that you used only supports CUDA 9.0.
https://www.tensorflow.org/install/source#tested_build_configurations

Would the replacement of GPU be the only option to train DH3D?

**Comment by JustWon** [comment]
I see.. that's why you asked to build tensoflow from the source.
I resolved it. Thanks!

**Comment by rui2016** [comment]
Hi @JustWon,

you are right, compiling TF from source will likely resolve the compatibility issue between TF and CUDA. Although the issue is closed, I'll post my configuration here in case it will be helpful to others.

GPU: GeForce RTX 2080 Ti 
CUDA: 10.1
Nvidia driver: 418.87.00
TensorFlow 1.9
Ubuntu 16.04

Cheers!
